// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"database/sql"
	"github.com/labstack/echo/v4"
	"github.com/ritarock/todo-app/adapter/delivery"
	"github.com/ritarock/todo-app/adapter/repository"
	"github.com/ritarock/todo-app/usecase"
	"time"
)

// Injectors from injector.go:

func Initialize(db *sql.DB, timeout time.Duration) (*echo.Echo, error) {
	taskRepository := repository.NewTaskRepository(db)
	taskUsecase := usecase.NewTaskUsecase(taskRepository, timeout)
	taskHandler := delivery.NewTaskHandler(taskUsecase)
	echoEcho := delivery.NewRouter(taskHandler)
	return echoEcho, nil
}
